name = "pagooz-ledger-local"
main = "../apps/ledger-worker/src/index.ts"
compatibility_date = "2026-03-06"
workers_dev = true

[vars]
ENVIRONMENT = "local"
APP_NAME = "pagooz-ledger"
APP_VERSION = "0.1.0"
GIT_SHA = "unknown"

[[d1_databases]]
binding = "DB"
database_name = "pagooz_d1_local"
database_id = "11111111-1111-1111-1111-111111111111"
migrations_dir = "./migrations"

[[queues.consumers]]
queue = "q-ledger-commands-local"
max_batch_size = 10
max_batch_timeout = 5

[[queues.producers]]
binding = "Q_LEDGER_EVENTS"
queue = "q-ledger-events-local"

[observability]
enabled = true

[env.dev]
name = "pagooz-ledger-dev"
workers_dev = true

[env.dev.vars]
ENVIRONMENT = "dev"
APP_NAME = "pagooz-ledger"
APP_VERSION = "0.1.0"
GIT_SHA = "unknown"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "pagooz_d1_dev"
database_id = "22222222-2222-2222-2222-222222222222"
migrations_dir = "./migrations"

[[env.dev.queues.consumers]]
queue = "q-ledger-commands-dev"
max_batch_size = 10
max_batch_timeout = 5

[[env.dev.queues.producers]]
binding = "Q_LEDGER_EVENTS"
queue = "q-ledger-events-dev"

[env.staging]
name = "pagooz-ledger-staging"
workers_dev = true

[env.staging.vars]
ENVIRONMENT = "staging"
APP_NAME = "pagooz-ledger"
APP_VERSION = "0.1.0"
GIT_SHA = "unknown"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "pagooz_d1_staging"
database_id = "33333333-3333-3333-3333-333333333333"
migrations_dir = "./migrations"

[[env.staging.queues.consumers]]
queue = "q-ledger-commands-staging"
max_batch_size = 10
max_batch_timeout = 5

[[env.staging.queues.producers]]
binding = "Q_LEDGER_EVENTS"
queue = "q-ledger-events-staging"

[env.prod]
name = "pagooz-ledger-prod"
workers_dev = true

[env.prod.vars]
ENVIRONMENT = "prod"
APP_NAME = "pagooz-ledger"
APP_VERSION = "0.1.0"
GIT_SHA = "unknown"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "pagooz_d1_prod"
database_id = "44444444-4444-4444-4444-444444444444"
migrations_dir = "./migrations"

[[env.prod.queues.consumers]]
queue = "q-ledger-commands-prod"
max_batch_size = 10
max_batch_timeout = 5

[[env.prod.queues.producers]]
binding = "Q_LEDGER_EVENTS"
queue = "q-ledger-events-prod"
