name = "pagooz-ledger-staging"
main = "apps/ledger-worker/src/index.ts"
compatibility_date = "2026-03-06"
workers_dev = true

[vars]
ENVIRONMENT = "staging"
APP_NAME = "pagooz-ledger"

[[d1_databases]]
binding = "DB"
database_name = "pagooz_d1_staging"
database_id = "COLE_AQUI_O_DATABASE_ID_DO_STAGING"

[[queues.consumers]]
queue = "q-ledger-commands"
max_batch_size = 10
max_batch_timeout = 5

[[queues.producers]]
binding = "Q_LEDGER_EVENTS"
queue = "q-ledger-events"

[observability]
enabled = trues